import type { Metadata } from "next";
import { Geist, Geist_Mono, Orbitron, Cinzel, Rajdhani, Share_Tech_Mono } from "next/font/google";
import SmoothScroller from "@/components/SmoothScroller";
import CustomCursor from "@/components/CustomCursor";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const orbitron = Orbitron({ variable: "--font-orbitron", subsets: ["latin"] });
const cinzel = Cinzel({ variable: "--font-cinzel", subsets: ["latin"] });
const rajdhani = Rajdhani({ variable: "--font-rajdhani", weight: ["300", "400", "500", "600", "700"], subsets: ["latin"] });
const shareTech = Share_Tech_Mono({ variable: "--font-share-tech", weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${orbitron.variable} ${cinzel.variable} ${rajdhani.variable} ${shareTech.variable} h-full antialiased dark`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col cursor-none overflow-x-clip bg-black text-white">
        <SmoothScroller>
          <CustomCursor />
          {children}
        </SmoothScroller>
      </body>
    </html>
  );
}
